/**
 * Refresh token data structure for entity creation and updates.
 */
export interface RefreshTokenData {
  /** Token identifier */
  readonly id: string;
  /** Associated user ID */
  readonly userId: string;
  /** The SHA-256 hash of the refresh token string */
  readonly tokenHash: string;
  /** Token creation date */
  readonly createdAt: Date;
  /** Token expiration date */
  readonly expiresAt: Date;
  /** Token revocation date (optional) */
  readonly revokedAt?: Date;
}

/**
 * Data structure for creating new refresh tokens.
 * Only userId and tokenHash are required, other fields are generated by the database.
 */
export type RefreshTokenCreateData = {
  readonly id: string;
  readonly userId: string;
  readonly tokenHash: string;
};

/**
 * Data structure for updating existing refresh tokens.
 * Only revokedAt can be updated.
 */
export type RefreshTokenUpdateData = {
  readonly id: string;
  readonly revokedAt: Date;
};
