services:
  app:
    container_name: ${APP_CONTAINER_NAME}-app
    restart: unless-stopped
    ports:
      - '${APP_PORT:-4200}:${APP_PORT:-4200}'
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    container_name: ${APP_CONTAINER_NAME}-postgres
    image: postgres:17.6-alpine
    restart: unless-stopped
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-nestjs-template-api}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    container_name: ${APP_CONTAINER_NAME}-redis
    image: redis:8.2-alpine
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis}
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
