services:
  # NestJS Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: unless-stopped
    ports:
      - '${APP_PORT:-4200}:${APP_PORT:-4200}'
    depends_on:
      - mariadb
      - redis
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  # MariaDB Database
  mariadb:
    image: mariadb:latest
    container_name: nestjs-mariadb
    restart: unless-stopped
    # Comment out ports for production - only internal access
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-nestjs}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nestjs_app}
      - MYSQL_USER=${MYSQL_USER:-nestjs}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nestjs}
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  # Redis Cache
  redis:
    image: redis:latest
    container_name: nestjs-redis
    restart: unless-stopped
    # Comment out ports for production - only internal access
    # ports:
    #   - "${REDIS_PORT:-6379}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis123}
    volumes:
      - redis_data:/data
    networks:
      - app-network

# Named volumes for data persistence
volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local

# Custom network
networks:
  app-network:
    driver: bridge
