services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:22-bookworm
    user: node
    working_dir: /workspaces/${APP_CONTAINER_NAME}
    volumes:
      - .:/workspaces/${APP_CONTAINER_NAME}:cached
    command: sleep infinity
    ports: []
