services:
  # NestJS Application - Development Override
  app:
  build: null
    image: mcr.microsoft.com/devcontainers/typescript-node:22-bookworm
    user: node
    working_dir: /workspaces/nestjs-app
    environment:
      - APP_ENV=development
      - PNPM_STORE_DIR=/workspaces/nestjs-app/.pnpm-store
    volumes:
      # Mount source code and dev caches into the container workspace folder
      - ..:/workspaces/nestjs-app:cached
      - node_modules:/workspaces/nestjs-app/node_modules
      - pnpm-store:/workspaces/nestjs-app/.pnpm-store

    command: sleep infinity # Keep container running

  # PostgreSQL - Expose port for development tools
  postgres:
    ports:
      - '5432:5432'

  # Redis - Expose port for development tools
  redis:
    ports:
      - '6379:6379'

volumes:
  node_modules:
  pnpm-store:
